### ISSUE TITLE
[FR] Different settings for different folder

### ISSUE THREAD

**Issue by Lisandra-dev** [trganda/obsidian-attachment-management#1]
It will be cool if we could add the option to add "override folder". 
For example, if an attachment is send in a specific folder, the processing will be different.

Use case : 
- I have some note that handle all illustration reference for my characters.
- To facilitate search, I created an attachment folder (named Illustration) next to this folder. 
- With these options, I just send the image in my folder note “Illustration” (with the MD path `Reference/Char 10/Illustration.md` and the file will be sent to `Reference/Char 10/Illustration/Image.png`

For the moment, I need to rename/move the image each time, and it's pretty unconvenient.

I also need to keep my `_assets` folder for attachment I don't need to move

**Comment by Lisandra-dev** [comment]
Thanks! <3

**Comment by trganda** [comment]
I have open a pull request for this feature,  you can try this feature right now, question and advice are welcome

If you have no building enviroment, you can download this pre-build plugin

- File: [obsidian-attachment-managment.zip](https://github.com/trganda/obsidian-attachment-management/files/11471267/obsidian-attachment-managment.zip)
- SHA512: 1CA6D65ABFFDDC6DCC94B249C5203ED9B3DC07A90E9644900AD12AA71246CA87A227425D6B6B5C336F579695DA1471E98BF0BC8B928CE48985C3AC123F40C008

**Comment by Lisandra-dev** [comment]
Tried but : 
 ```
 22:41:39.672 Override Settings, 20. REFERENCES/22. Personnages/Ashling May/Illustration.md: [object Object]
plugin:attachment-management:286 22:41:51.081 On Create Event - File: _assets/download20190702230706.png
plugin:attachment-management:286 22:41:51.081 Active File Path 20. REFERENCES/22. Personnages/Ashling May/Illustration.md
plugin:attachment-management:286 22:41:51.081 New Path of File: _assets/20. REFERENCES/22. Personnages/Ashling May/IMG-2023-05-15.png
plugin:attachment-management:286 22:41:51.173 Source Path of Rename: _assets/download20190702230706.png
plugin:attachment-management:286 22:41:51.173 Destination Path of Rename: _assets/20. REFERENCES/22. Personnages/Ashling May/IMG-2023-05-15.png
plugin:attachment-management:286 22:41:51.173 replace text ![[download20190702230706.png]] ![[download20190702230706.png]]
plugin:obsidian-icon-folder:2378 element with data path not found _assets/Illustration-15-05-2023.png
plugin:attachment-management:286 22:41:51.187 On Rename Event - New Path and Old Path: _assets/Illustration-15-05-2023.png _assets/download20190702230706.png
plugin:attachment-management:286 22:41:51.187 RenameType: RENAME_EVENT_TYPE_FILE
plugin:attachment-management:286 22:41:51.187 Old Note Path: _assets
plugin:attachment-management:286 22:41:51.187 Old Note Name: download20190702230706
plugin:attachment-management:286 22:41:51.187 Old Attachment Path: _assets/_assets
plugin:attachment-management:286 22:41:51.187 New Attachment Path: _assets/_assets
app.js:1 Sync Error!
app.js:1 Error: ENOENT: no such file or directory, open 'K:\Constellation\_assets\download20190702230706.png'
plugin:attachment-management:286 22:41:51.202 Attachment path does not exist: _assets/_assets
app.js:1 Uncaught (in promise) Error: Destination file already exists!
    at e.<anonymous> (app.js:1:601991)
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
plugin:customizable-menu:224 Épingler
plugin:customizable-menu:224 Copier l'url Obsidian
plugin:customizable-menu:224 Lint file
plugin:customizable-menu:224 Ouvrir les rétroliens
plugin:customizable-menu:224 Ouvrir les liens sortants
plugin:attachment-management:286 22:42:32.095 
{attachmentRoot: 'Illustration', saveAttE: 'nextToNote', attachmentPath: '${notename}', attachFormat: '${notename}-${date}', type: 'FILE'}
attachFormat
: 
"${notename}-${date}"
attachmentPath
: 
"${notename}"
attachmentRoot
: 
"Illustration"
saveAttE
: 
"nextToNote"
type
: 
"FILE"
[[Prototype]]
: 
Object
````

**Comment by Lisandra-dev** [comment]
It seems that the plugin crash the renaming if the destination path (folder) already exists.

**Comment by trganda** [comment]
Yes, this plugin has no increment number for duplicate files right now (as you mentioned in [[BUG] Image name are not incremented](https://github.com/trganda/obsidian-attachment-management/issues/4))
In my original plan, it will be implement after the override setting, but I have ignored some use cases and lead this problem.

And after review my code, I have found more problem.
I will fix these bugs as soon as possible. :)

**Comment by trganda** [comment]
I rewrite some code and make the override setting work. For the duplicate files problem will  processing in a new pull request.

For the override setting, I have tried to test some use case:

- [x] The priority of overriding setting
- [x] Update overriding setting data on rename a folder or file
- [x] After set overriding setting, paste or drop file to notes

I hope this can make this feature working as expected.

**Comment by Lisandra-dev** [comment]
I will try it ! Thanks :D

**Comment by Lisandra-dev** [comment]
THANKS! 
Works as expected now.

As I know a little in the dev of Obsidian Plugin, I made some update (notably checkCallback for commands). I will made a PR in your Prod branch!

**Comment by trganda** [comment]
Happy to hear that!
And PR are welcome, I'wll merge this PR first.
