### ISSUE TITLE
Image Extension Renaming Failed

### ISSUE THREAD

**Issue by kennygokh** [trganda/obsidian-attachment-management#126]
Hi, with the latest update of Obsidian to 1.6.3, I noticed that auto renaming does not work anymore. To elaborate in details, when I add an image file, it is supposed to rename to IMG-ddmmyyhhmmss format that I have setup. What happen is that it created a "[](original image filename)" and place in the first line of the note. It even breaks the YAML --- line. The image file name did not rename. Please help to check.

**Comment by trganda** [comment]
Hi @kennygokh, can you provide your configuration file of this plugin, it's under `.obsidian/plugins/attachment-management/data.json`. And I can not reproduce your situation, it's better if you can upload a screenshot or video

**Comment by trganda** [comment]
You could try to upgrade to Obsidian v1.6.4 and higher, this is the bug of Obsidian, please refer https://obsidian.md/changelog/2024-06-20-desktop-v1.6.4/

**Comment by kennygokh** [comment]
Thanks. It looks ok now. I will continue to monitor.
