### ISSUE TITLE
移动文件时，对 callouts 框内附件链接的自动修改会导致错误

### ISSUE THREAD

**Issue by DHDouglas** [trganda/obsidian-attachment-management#127]
版本：Obsidian v1.6.3，最新插件版本

将笔记文件从 `/Dir A` 目录移动到 `/Dir B` 目录

## 正常情况

文件移动前：

<img width="455" alt="Snipaste_2024-06-18_17-40-02" src="https://github.com/trganda/obsidian-attachment-management/assets/58352730/6f7fc873-9070-45d0-a5b5-fb329bcc2b76">

文件移动后：

<img width="415" alt="Snipaste_2024-06-18_17-40-15" src="https://github.com/trganda/obsidian-attachment-management/assets/58352730/5cf05fef-7b26-45ee-893f-948b278114b9">

## 异常情况

下述情况仅在 "callouts" 框自定义了标题时会触发。在未自定义标题时则如上图是正常的。

文件移动前：  

<img width="378" alt="Snipaste_2024-06-18_17-40-59" src="https://github.com/trganda/obsidian-attachment-management/assets/58352730/9dbc1289-b011-4194-88a4-c9e491a1a598">

<img width="470" alt="Snipaste_2024-06-18_17-41-15" src="https://github.com/trganda/obsidian-attachment-management/assets/58352730/539edbd8-ed22-44e8-a89b-73a2cc1236c8">

文件移动后：附件被同步移动了，但是在对笔记文件内的 "引用链接" 自动修改时出现了以下情况

<img width="541" alt="Snipaste_2024-06-18_17-41-30" src="https://github.com/trganda/obsidian-attachment-management/assets/58352730/d60f8746-23cc-47a4-bdf2-d7b9570f4946">

<img width="539" alt="Snipaste_2024-06-18_17-41-43" src="https://github.com/trganda/obsidian-attachment-management/assets/58352730/a59eff63-6051-459b-bc20-7f7510d5c131">

**Comment by jack2game** [comment]
I'm experiencing the same issue.

Would greatly appreciate a fix. I'm also using PDF++ with tons of callouts and links from PDF files.

Not being able to update the links properly is unfortunately seriously impacting my workflow right now... It used to work fine but not any more.

**Comment by trganda** [comment]
@DHDouglas  我测试了一下确实是这种情况，甚至有更怪异的行为。请问你是在更新到 1.6.3 之后遇到的吗？还是之前的旧版本也有这种问题？

**Comment by trganda** [comment]
@jack2game @DHDouglas it's a bug of the Obsidian, please upgrade to latest version Obsidian,

**Comment by jack2game** [comment]
Thanks. I can see the issue goes away for now, after updating to v1.6.5

**Comment by DHDouglas** [comment]
非常感谢，obsidian 更新到1.6.5 后已解决
