### ISSUE TITLE
Obsidian crashes when attaching files if “Attachment path” is empty

### ISSUE THREAD

**Issue by ghost** [trganda/obsidian-attachment-management#142]
Thanks for the great plugin!

Maybe related to #105.

I like a flat file structure. I want all notes and attachments to be in the root folder of the vault, so I tried to attach files with the “Attachment Path” setting empty, but it fails. When I attach a file, Obsidian crashes, automatically restarts and displays the vault selection screen.

After selecting the Vault, it is a mixed bag. Sometimes the images are renamed correctly, sometimes not. You may also end up with two images, one before and one after the renaming.

At least from what I have tried with my vault and Sandbox Vault, it seems that the “Attachment path” setting in this plugin is causing this crash. The default `${notepath}/${notename}` works as expected without crashing, but if empty it crashes. How do I set up an attachment to be placed in the root folder of the Vault?

Here is my Debug info:

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Everforest Enchanted v3.12.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 5
		1: Auto Template Trigger v1.2.2
		2: Update modified date v1.3.2
		3: Code Editor Shortcuts v1.14.0
		4: Editor Commands Remap v1.0.2
		5: Attachment Management v0.9.12
```
To reproduce in Sandbox Vault:

- Start Sandbox Vault.
- Install this plugin.
- Set "Attachment path" to empty. All other settings are left as default.
- If you paste an image at random, it will crash.

**Comment by trganda** [comment]
@gqszds , can you provide your configuration file of the plugin? It's located in `.obsidian/plugins/attachment-management/data.json`

**Comment by trganda** [comment]
Fixed in https://github.com/trganda/obsidian-attachment-management/pull/143, you can upgrade to latest version.
