### ISSUE TITLE
Image Renaming feature does not work in certain scenarios

### ISSUE THREAD

**Issue by ZHmao** [trganda/obsidian-attachment-management#147]
The first picture you paste on a note, it always couldn't be renamed.

OS version: macOS 14.5
Obsidian: Version 1.6.7 (Installer 1.5.8)
Attachment management: 0.9.13

**Comment by luckman212** [comment]
Maybe related or duplicate of #145

**Comment by trganda** [comment]
Looks like I have introduced a new bug, I have also encounter this bug. I will try to fix it 😢

**Comment by trganda** [comment]
> Maybe related or duplicate of #145

Looks like you are right, tks for your tips

**Comment by ZHmao** [comment]
thank you. 💯
