### ISSUE TITLE
Add command to "Rename attachments within current file"

### ISSUE THREAD

**Issue by luckman212** [trganda/obsidian-attachment-management#29]
- Obsidian 1.3.5
- attachment-management v0.5.5

It would be amazing to have be able to manually trigger the plugin to rename & reorganize the attachments within the **currently active file**.

By mistake, I triggered the _"Rearrange linked attachments"_ action, and it re-organized my entire vault 😱

(awesome plugin by the way, thank you!)

**Comment by trganda** [comment]
Tks for your feedback, "Rearrange" feature was under experiment right now.

The "Rearrange linked attachments" action was only working for active file right now.
Another action "Rearrange all linked attachments" was added to replace the original action.

**Comment by trganda** [comment]
Please upgrate to https://github.com/trganda/obsidian-attachment-management/releases/tag/0.6.0

**Comment by luckman212** [comment]
Thank you, I updated to 0.6.0 and I did test the new command. It works, but only moves the existing files into their subfolder, but does not rename them. Is there any way to also trigger the function that renames the attachments to keep them consistent? (i.e. the same thing that would happen if you manually cut & then re-pasted each image in a file)

**Comment by trganda** [comment]
It's a mistake of my function,  I have fixed in https://github.com/trganda/obsidian-attachment-management/releases/tag/0.6.1.

**Comment by trganda** [comment]
Glad to hear it, feedback are welcome
