### ISSUE TITLE
Feature Req: Ability to exclude paths

### ISSUE THREAD

**Issue by spiritualgeek** [trganda/obsidian-attachment-management#33]
Love this plugin. It's a lifesaver for anyone that stores files/docs alongside their notes.

I have a small request

Could you please introduce the ability to exclude a list of paths?

While you work on this, it would be good to quickly introduce a shortcut to switch off and on

**Comment by trganda** [comment]
What's your expected behavior of the exclude paths? 

Do nothing and use the default operation of the obsidian?

**Comment by spiritualgeek** [comment]
Correct as you stated: "_Do nothing and use the default operation of the obsidian_"

**Comment by trganda** [comment]
I will try to add this feature in next minor version.

**Comment by spiritualgeek** [comment]
Appreciate it

**Comment by Raagaception** [comment]
+1, really in need of this feature!

**Comment by trganda** [comment]
It's late but coming, you can now upgrade to https://github.com/trganda/obsidian-attachment-management/releases/tag/0.7.2.
I have do some testing on my machine, if you have found some bug or problem, please tell me.
