### ISSUE TITLE
[BUG] attachment path empty

### ISSUE THREAD

**Issue by juestchaos** [trganda/obsidian-attachment-management#34]
After setting the attachment path to empty, it is not possible to automatically modify the previously attached files uniformly.

**Comment by trganda** [comment]
The rename operation will processing the file on the attachment path that generate from the current plugin settinig, not the linked file of your markdown or canvas.

That's meaning, if you already have some attached file before using this plugin, or you have attached file to the document but modifed the setting in future. The attached file **before modify setting** will not be cover.

If your want to arrange your attached file after modifed setting, use the `Rearrange linked attachments` command for current active file or `Rearrange all linked attachments` (remeber to backup your vault first, this command will introduce a lot change) for all file.

> Why not make the rename operation work on linked attached file but path? For saving time, I don't think people will always change the setting of attachment.
