### ISSUE TITLE
[BUG] Image name are not incremented

### ISSUE THREAD

**Issue by Lisandra-dev** [trganda/obsidian-attachment-management#4]
Noticed that the image name is not incremented if multiple image are send in the same time, for example with `YYYY-MM-DD`

**Comment by trganda** [comment]
This problem will be in fix in [Add override setting](https://github.com/trganda/obsidian-attachment-management/pull/3)

**Comment by Lisandra-dev** [comment]
At last, the `x` for date format can help for that!

**Comment by trganda** [comment]
It's now support on version [0.4.0](https://github.com/trganda/obsidian-attachment-management/releases/tag/0.4.0).
