### ISSUE TITLE
[FR] Mobile

### ISSUE THREAD

**Issue by Lisandra-dev** [trganda/obsidian-attachment-management#5]
Also, the plugin can be useful on mobile version. Unfortunately, the `path` is from node. Node is unsupported on mobile.
https://marcus.se.net/obsidian-plugin-docs/reference/typescript/functions/normalizePath#parameters exists on Obsidian native, so you can use it.

**Comment by Lisandra-dev** [comment]
Btw, you could use directly `TFile` in needToRename, with for example, `sourceFile` so you can get ride of `path.posix` to use native TFile/TFabstract (.ext…)
Ex : 
```ts
    const oldNote = this.app.vault.getAbstractFileByPath(oldPath) as TFile;
    // generate old note path and name
    const oldNotePath = oldNote?.path as string;
    const oldNoteExtension = oldNote?.extension as string;
    const oldNoteName = oldNote?.basename as string;
    ```

Also, if file doesn't exists, I have some little function to get for example, the basename : 
```ts
const basename = (name: string) => /([^/\\.]*)(\..*)?$/.exec(name)[1];
```

**Comment by trganda** [comment]
I have replaced the nodejs path library with a build in path lib.
