### ISSUE TITLE
Enhancement: Attachment Sequence

### ISSUE THREAD

**Issue by hrxkr** [trganda/obsidian-attachment-management#50]
The `Attachment Format` was assigned as `${notename}` in the plugin settings.

Eg. Note named "try-attachment"

**Actual**
The attachment seq. generated was _try-attachment_, _try-attachment-1_, _try-attachment-2_....

**Expected**
The attachment seq. to be _try-attachment-1_, _try-attachment-2_, _try-attachment-3_.... 

It would be neat if the sequence number (1) is assigned from the very first attachment. 

---

Thanks for a fantastic utility plugin 👍

**Comment by trganda** [comment]
Hi @hrxkr , the suffix number was added for duplicate file name if there is already an attachment with name `try-attachment`. But, we don't konw whether there will be more same file add to one folder.

So, there is no reason to add a number `1` to the attachment that be firstly placed. Hope you understand.
