### ISSUE TITLE
[FR]: Overrides path by extensions

### ISSUE THREAD

**Issue by Lisandra-dev** [trganda/obsidian-attachment-management#56]
The overrides is great, but it doesn't difference between pdf and image, for example (if we handle all attachment). It will be cool to have a button to set custom path by extension in the settings and overrides settings.

The idea is to add a `plus` button, that populate a list. In the creating path, check the extension. If the extension exist in the list of the overrides or normal settings, apply the path instead of the default one. 

It allow classifying better. For example, it allows me to move automatically all my PDF into `_assets/pdf/{filename}`

**Comment by trganda** [comment]
I have the similar ideas but never plan. Tks for your request, I will rewrite this feature by refer your code. :)

**Comment by trganda** [comment]
Hi @Lisandra-dev, you can try to upgrade to [0.8.3](https://github.com/trganda/obsidian-attachment-management/releases/tag/0.8.3) and test this feature.
