### ISSUE TITLE
[FR] : Toggle to handle all extensions versus only certain ones

### ISSUE THREAD

**Issue by spiritualgeek** [trganda/obsidian-attachment-management#63]
Hi

I've become so reliant on this plugin. Thank you

With the last update, it seems as if I need to give the plugin all the extensions I want it to handle?

Is there not a way to have a toggle

1. Handle all extensions
2. Handle only these extensions

Thanks

**Comment by trganda** [comment]
Hi, @spiritualgeek , the old **Handle all" option has been deprecated

If you want to handle all extension, click the **Add extension overrides**, and add a new items with extension **.\*** (regex expression, mean match all extension). 

> You can put a regex expression in the text field of extension overrides.

I'm sorry for confuses the configuration, the document will be improve.
