### ISSUE TITLE
Not sure what to call this, probably not a bug, related to multiple formats on pasteboard

### ISSUE THREAD

**Issue by luckman212** [trganda/obsidian-attachment-management#64]
Hi @trganda 

I updated my Attachment Management to 0.8.3 and faced a surprising problem. 

I use CleanShot X to edit images/screenshots before pasting into Obsidian. I noticed that the images I edited/copied from CleanShot were no longer being handled.

I found https://github.com/trganda/obsidian-attachment-management/issues/63 issue and when I added the `.*` override, it started working again.

<img width="744" alt="image" src="https://github.com/trganda/obsidian-attachment-management/assets/1992842/91966f5f-27fd-494d-b161-3fbd0192cbe9">

Is this the recommended solution? Just wanted to know if this was correct. Thank you!

Here is the difference, fyi, for these objects in the pasteboard, I used [Pasteboard Viewer](https://apps.apple.com/us/app/pasteboard-viewer/id1499215709?mt=12) to display it.

original png image, copied and pasted (works fine). types are _only_ `public.png`
<img width="869" alt="screen 0" src="https://github.com/trganda/obsidian-attachment-management/assets/1992842/1a04ccdf-c351-490f-bb95-c9fe62d38a78">

edit this image in CleanShot, add a line for example, and copy it
<img width="802" alt="screen 1" src="https://github.com/trganda/obsidian-attachment-management/assets/1992842/b6cfb9e6-d537-4387-96fc-183755f87bd8">

after copying from CleanShot, this is the object, types are types are `public.png` and `public.file-url`
<img width="879" alt="screen 2" src="https://github.com/trganda/obsidian-attachment-management/assets/1992842/2a45172c-ceba-4d61-8c72-2501e69d2bb7">

pasting into Obsidian, it is no longer handled by the plugin
<img width="872" alt="screen 4" src="https://github.com/trganda/obsidian-attachment-management/assets/1992842/21509ec7-fd2b-4a32-815f-5ea88cdd1c56">

**Comment by trganda** [comment]
Hi @luckman212 , sorry for that. It's a bug exactly.

In default, this plugin should be only working on images extension, with pattern expression `(jpe?g|png|gif|svg|bmp|eps|webp)`. And I have fixed it in [0.8.4](https://github.com/trganda/obsidian-attachment-management/releases/tag/0.8.4).

The soluation in https://github.com/trganda/obsidian-attachment-management/issues/63 was for handle all extension file.

**Comment by trganda** [comment]
So, If you if you don't need to handle all extension, delete the extension override you already added with pattern `.*`.

**Comment by luckman212** [comment]
Thanks @trganda I will re-try it!
