### ISSUE TITLE
[FR] Use parent folder instead of filename

### ISSUE THREAD

**Issue by Lisandra-dev** [trganda/obsidian-attachment-management#7]
For the moment, there is no way to use the `foldername` instead of the `filename`. I will love to have the option to use the parent folder, as a variable in the settings.

You can easily get it with `file.parent` on TFabstractFile (https://docs.obsidian.md/Reference/TypeScript+API/TAbstractFile/TAbstractFile)

**Comment by trganda** [comment]
I will add more variable in the future

**Comment by trganda** [comment]
This feature was added in https://github.com/trganda/obsidian-attachment-management/pull/12
