### ISSUE TITLE
Hide attachment folder

### ISSUE THREAD

**Issue by znning** [trganda/obsidian-attachment-management#74]
Whether the hidden folder feature can be developed

**Comment by ViGeng** [comment]
I found I can not set an attachment path like:`${notepath}/.assets`
Could you please consider fixing this? Thx!

**Comment by trganda** [comment]
> I found I can not set an attachment path like:`${notepath}/.assets` Could the author please consider fixing this? Thx!

I will take a look

**Comment by trganda** [comment]
> Could the author please consider fixing this? Thx!

I have do some testing, we could create a `hidden` folder in ob, but we can not get it

<img width="528" alt="image" src="https://github.com/trganda/obsidian-attachment-management/assets/62204882/00bc38b8-5263-467f-9c59-bfd969199637">

However, this plugin was based on the api `app.vault.getAbstractFileByPath`. I will report it to ob or find out other solution.
