### ISSUE TITLE
Saving images by date

### ISSUE THREAD

**Issue by Hela-Girl** [trganda/obsidian-attachment-management#80]
Hi
Is it possible to configure so that the added images are not just saved in the “images” folder, but in a subfolder but with the date the image was added “images\05-11-23”

I just need to save images by date, then I will clearly understand by folder which image I added when, and it will also get rid of garbage in the “images” folder

**Comment by trganda** [comment]
Answered in discussion https://github.com/trganda/obsidian-attachment-management/discussions/79
