### ISSUE TITLE
ob整套文件夹都在smb共享文件夹中，插件不能成功重命名文件

### ISSUE THREAD

**Issue by Howardnm** [trganda/obsidian-attachment-management#82]
ob整套目录在本地文件夹中，可以正常运行。
但是ob目录在smb共享文件夹中，插件不能成功重命名文件

是不是跟下面smb的路径格式有关系？
\\nas\obsidian

**Comment by trganda** [comment]
插件都是调用 ob 提供的接口进行目录或文件重命名的，ob 会告诉插件当前 vault 下有哪些文件，目录结构是怎么样的。我也不太清楚为什么在 smb 的目录下就会失败。
