### ISSUE TITLE
Attachment does not automatically renamed (bug)

### ISSUE THREAD

**Issue by neins** [trganda/obsidian-attachment-management#85]
Hello. Plugin doesn't change path of corresponding attachment

I choose these settings for attachments:
**Obsidian settings**:
Files and links -> Save new attachments in vault root by default
**Plugin settings**:
Save in the folder specified below
Root folder: _attachments
Attachment path: ${notepath}/${notename}
Attachment format: ${notename}-${originalname}
Automatically rename attachment: is set

<details>
 <summary>(trying to use hidden folder .attachments)</summary>
I tried to use hidden named folder .attachments but unfortunately it working in half way. Plugin creates all folders by the .attachment/${notepath} pattern but the attachment file always appear in vault folder and not renamed by attachment format
</details>

There is simple structure for example:
<img width="167" alt="image" src="https://github.com/trganda/obsidian-attachment-management/assets/22091732/6f85c87b-1cc5-4d36-9082-dfdc9079d563">

When I attach some image to the note the plugin creates corresponding path: _attachments/projects/1/note/note-0.png
But when I move (and/or rename) _note.md_ from folder _1_ to folder _2_ I expect that attachment(s) will be automatically update its path, but it is still remain in the same location in _attachments

Should _Automatically rename attachment_ setting work in this scenario?

**Comment by trganda** [comment]
Thinks for report this problem.

Of course the `Automatically rename attachment setting` should be working in this case. This bug was case by some problme of obsidian cache, I will fix it.

**Comment by neins** [comment]
Yes, I re-enabled the plugin and it is works perfectly. Thank you
