### ISSUE TITLE
${originalname} seems to be broken

### ISSUE THREAD

**Issue by OsoRojo** [trganda/obsidian-attachment-management#87]
I'm unable to use ${originalname} in conjunction with any other format parameters.  In fact it seems to just not work at all.  

Example: 

Image file named "foo.jpg"
Attachment format of: ${originalname} - ${date}
Result: foo-1.jpg

Additionally, originalname doesn't appear to be supported in extension overrides, which is where I really need them the most.  At least the dialog doesn't list it as an option, and it definitely doesn't work.  I don't know if this is intended or an oversight.

**Comment by trganda** [comment]
> I'm unable to use ${originalname} in conjunction with any other format parameters. In fact it seems to just not work at all.

Looks like the `${date}` was not working right. Can you provide your setting (a data.json file in `.obsidian/plugins/attachment-management`) of this plugin?

I have tested your example, it's work.

<img width="675" alt="image" src="https://github.com/trganda/obsidian-attachment-management/assets/62204882/767c96e8-5213-422f-a631-b3b0eb725fed">

> Additionally, originalname doesn't appear to be supported in extension overrides

I have forgot to update the description, your can also use `${originalname}` in overrides.

**Comment by OsoRojo** [comment]
See attached.  I just removed the plugin and reinstalled, and I'm getting the same result.  Extension overrides that include date as noted above just result with the original filename (which is good) and a '-1' at the end instead of the date (which is bad).

Also, as previously noted using originalname either isn't working, OR it cannot be combined with other options.  I just tested that again in the base settings (not an extension override) and it moves the file fine, but no renaming occurs.  Use case:  ${originalname} - ${date}

[data.json](https://github.com/trganda/obsidian-attachment-management/files/13728480/data.json)

**Comment by OsoRojo** [comment]
I should have noted, this is occurring when I'm running the rearrange attachments command, NOT on attachment insertion (paste).  I just noticed that the combination of `${originalname} - ${date}` does appear to work when pasting in images, but not when running the rearrange attachments command.

**Comment by trganda** [comment]
The variable `${originalname}` has a flaw, since I have not presist the origianl name of an attachment when it was added to notes. When you add an attachment to ob, we could simply know the name of the attachment. But in the rename (rearrange) operation, this plugin didn't know the origanl name and just return current name (ignore all variable). The suffix `-1` was added for deduplicate.

I will make a PR to complete the implemention of `${originalname}`. You can temporarily disable this plugin if other variable was not meet your needs.

**Comment by OsoRojo** [comment]
It seems to me in this case that using the current name as the original name would probably make the most sense.  At least, that's the behavior I was sort of expecting.  Glad that the additional context (rearrange vs. new insertion) helped to sort it out!  

Loving the plugin so far.  Just trying to find the best way to leverage it! 

Thanks!
