### ISSUE TITLE
Renaming note creates folder structure with new folder instead of renaming the old one

### ISSUE THREAD

**Issue by iLexxG** [trganda/obsidian-attachment-management#89]
Hi!
I have the latest versions of Obsidian (1.5.3) and Attachment Management (0.9.1). 
Attachment path in plugin is set by default (i've also tried to changing it):
```
${notepath}/${notename}
```
I've made test note - Note1 with some random attachment and it work as expected:
![image](https://github.com/trganda/obsidian-attachment-management/assets/81971473/26785b64-0765-4508-a404-c2d036b29633)
Then I'm trying to rename Note1 => Note2 and expecting that attachment folder Note1 will become Note2 with that .png file. But instead I get an empty Note1 folder and Note2 folder with attachment:
![image](https://github.com/trganda/obsidian-attachment-management/assets/81971473/df299387-b244-4754-8841-2ced85683eba)
Seems like misunderstood something or misconfig?
Thanks!

**Comment by trganda** [comment]
Fixed in latest version, the old folder will be remove if it's empty.
