### ISSUE TITLE
Excalidraw中图片重命名第一次粘贴时会失效

### ISSUE THREAD

**Issue by PandaNocturne** [trganda/obsidian-attachment-management#91]
大大你好，在Excalidraw中粘贴图片时，附件重命名有时间会在粘贴后，会失效，就是Excalidraw没来的及更改，Excalidraw有缓存原因，图片不会第一时间失效，导致下次进入Excalidraw图片直接是无效的图片，能否告知一些解决方案，或者插件适配一下Excalidraw画板吗

**Comment by trganda** [comment]
目前还不支持 Excalidraw 画板，它的图片链接格式是 Wikilink `[[]]`，不会跟随 ob 的设置改变。临时方案可以修改ob设置，开启 Wikilink 格式的链接。

**Comment by PandaNocturne** [comment]
好的，谢谢
