### ISSUE TITLE
Automatic save and rename doesn't work for PDF files

### ISSUE THREAD

**Issue by TomieH** [trganda/obsidian-attachment-management#93]
I am using version 0.9.1
with this setting.
![image](https://github.com/trganda/obsidian-attachment-management/assets/42717368/b112e4e8-e672-4e2c-ab12-e22320f67f36)
all files I drop in my notes will be renamed and stored in the archive folder except the *.pdf files. These files will not be renamed and moved to the archiv folder. 

I am not quite sure what my mistake is or is it a bug?

**Comment by trganda** [comment]
> I am not quite sure what my mistake is or is it a bug?
By default, it's only processing the image file, if your want to support pdf, using the **Add extension overrides** to add a config fo pdf file.
