### ISSUE TITLE
重命名 canvas 附件路径不会修改，控制台报错。

### ISSUE THREAD

**Issue by Finish02** [trganda/obsidian-attachment-management#95]
大佬你好，我发现重命名 canvas 附件路径不会修改，控制台报错。
具体流程：
新建白板 -> 粘贴图片 -> 点击左上角选择重命名 -> 重命名后，附件路径不会修改，控制台报错。
Obsidian 版本：1.5.3
插件版本：0.9.1

![1](https://github.com/trganda/obsidian-attachment-management/assets/50348289/ee27905c-5b38-4f9d-95e2-56d3b5a7e908)

**Comment by trganda** [comment]
更新一下插件再试试
